#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE=".env.aws"
AWS_REGION="ap-northeast-2"
CERTIFICATE_REGION="us-east-1"
BASE_DOMAIN="hyunbeom.site"
CUSTOM_DOMAIN="www.$BASE_DOMAIN"
PUBLIC_URL="https://$CUSTOM_DOMAIN"
AWS_STACK="joblens-test-runtime"
GITHUB_REPOSITORY="hyunbeomlee1227-dev/joblens"

banner "JobLens custom domain setup"

stage "Confirm AWS access and the existing distribution"
for command in aws curl gh; do
  if ! command -v "$command" >/dev/null 2>&1; then
    warn "$command is required before continuing."
    exit 1
  fi
done
if ! gh auth status --hostname github.com >/dev/null 2>&1; then
  say "GitHub needs a browser sign-in so the final deployment address can be updated."
  gh auth login --hostname github.com --web
fi
if ! aws sts get-caller-identity >/dev/null 2>&1; then
  say "The saved AWS session has expired. AWS will open a browser for sign-in."
  aws login
fi
AWS_ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
DISTRIBUTION_ID="$(aws cloudformation describe-stacks --region "$AWS_REGION" --stack-name "$AWS_STACK" --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue | [0]" --output text)"
CLOUDFRONT_DOMAIN="$(aws cloudfront get-distribution --id "$DISTRIBUTION_ID" --query 'Distribution.DomainName' --output text)"
say "AWS account: $AWS_ACCOUNT_ID"
say "CloudFront: $CLOUDFRONT_DOMAIN"
say "Custom address: $PUBLIC_URL"
if ! confirm "Attach $CUSTOM_DOMAIN to this existing JobLens distribution?"; then
  say "No AWS or DNS settings were changed."
  exit 0
fi

stage "Request or reuse the HTTPS certificate"
CERTIFICATE_ARN="$(aws acm list-certificates \
  --region "$CERTIFICATE_REGION" \
  --certificate-statuses PENDING_VALIDATION ISSUED \
  --query "CertificateSummaryList[?DomainName=='${CUSTOM_DOMAIN}'].CertificateArn | [0]" \
  --output text)"
if [[ -z "$CERTIFICATE_ARN" || "$CERTIFICATE_ARN" == "None" ]]; then
  CERTIFICATE_ARN="$(aws acm request-certificate \
    --region "$CERTIFICATE_REGION" \
    --domain-name "$CUSTOM_DOMAIN" \
    --validation-method DNS \
    --idempotency-token JobLensWwwDomain \
    --options CertificateTransparencyLoggingPreference=ENABLED \
    --tags Key=Project,Value=JobLens \
    --query CertificateArn \
    --output text)"
fi
write_env CUSTOM_DOMAIN "$CUSTOM_DOMAIN"
write_env ACM_CERTIFICATE_ARN "$CERTIFICATE_ARN"

VALIDATION_NAME=""
for _ in $(seq 1 15); do
  VALIDATION_NAME="$(aws acm describe-certificate --region "$CERTIFICATE_REGION" --certificate-arn "$CERTIFICATE_ARN" --query 'Certificate.DomainValidationOptions[0].ResourceRecord.Name' --output text)"
  [[ -n "$VALIDATION_NAME" && "$VALIDATION_NAME" != "None" ]] && break
  sleep 2
done
if [[ -z "$VALIDATION_NAME" || "$VALIDATION_NAME" == "None" ]]; then
  warn "AWS did not produce the DNS validation record. Re-run this wizard in a minute."
  exit 1
fi
VALIDATION_VALUE="$(aws acm describe-certificate --region "$CERTIFICATE_REGION" --certificate-arn "$CERTIFICATE_ARN" --query 'Certificate.DomainValidationOptions[0].ResourceRecord.Value' --output text)"
VALIDATION_NAME="${VALIDATION_NAME%.}"
VALIDATION_VALUE="${VALIDATION_VALUE%.}"
VALIDATION_HOST="${VALIDATION_NAME%.$BASE_DOMAIN}"
write_env ACM_VALIDATION_NAME "$VALIDATION_NAME"
write_env ACM_VALIDATION_VALUE "$VALIDATION_VALUE"

stage "Add the certificate CNAME in DNSZi"
say "DNSZi login details stay in the browser and are never captured here."
open_url "https://dnszi.com/"
step "Sign in, choose $BASE_DOMAIN, and open CNAME record management."
step "Add a CNAME record with host/name: $VALIDATION_HOST"
step "Set its destination/value to: $VALIDATION_VALUE"
step "If DNSZi previews the full record, confirm it becomes $VALIDATION_NAME (not a duplicated domain)."
pause "Save the record in DNSZi, then press Enter."

stage "Validate HTTPS and attach the domain to CloudFront"
say "AWS will wait for the public DNS record and then update the existing distribution."
aws acm wait certificate-validated --region "$CERTIFICATE_REGION" --certificate-arn "$CERTIFICATE_ARN"
if ! confirm "The certificate is valid. Update the production CloudFront distribution now?"; then
  say "The certificate remains available; CloudFront was not changed."
  exit 0
fi
aws cloudformation deploy \
  --region "$AWS_REGION" \
  --stack-name "$AWS_STACK" \
  --template-file infra/aws/runtime.yml \
  --capabilities CAPABILITY_IAM \
  --no-fail-on-empty-changeset \
  --parameter-overrides \
    CustomDomainName="$CUSTOM_DOMAIN" \
    AcmCertificateArn="$CERTIFICATE_ARN"
aws cloudfront wait distribution-deployed --id "$DISTRIBUTION_ID"

stage "Point www to CloudFront in DNSZi"
open_url "https://dnszi.com/"
step "Choose $BASE_DOMAIN and open CNAME record management."
step "Add host/name: www"
step "Set destination/value to: $CLOUDFRONT_DOMAIN"
step "Do not add http:// or https://, and remove a trailing dot if DNSZi rejects it."
pause "Save the www CNAME record, then press Enter."

stage "Redirect the HTTP root domain to www"
say "DNSZi's public guide calls this 포워딩 설정 and documents an address-redirect mode."
say "DNSZi forwards HTTP requests to an HTTPS destination; it does not provide a TLS certificate for the root domain."
say "The current signed-in dashboard is not publicly visible, so stop instead of guessing if its labels differ."
open_url "https://dnszi.com/notice_view.html?no=3808&page=2&searchField=title&searchValue="
step "Review DNSZi's published root-domain forwarding instructions, then return to the DNSZi dashboard."
open_url "https://dnszi.com/"
step "Choose $BASE_DOMAIN and open the 포워딩 설정 or 웹 포워딩 section named by DNSZi."
step "Configure the HTTP root domain (blank host or @) to forward to $PUBLIC_URL."
step "Choose https:// for the destination and permanent redirect (301)."
step "Do not use masked/frame forwarding."
if ! confirm "Does the saved rule explicitly show destination $PUBLIC_URL and permanent redirect (301)?"; then
  warn "The required forwarding rule is not confirmed. No GitHub deployment address was changed."
  exit 1
fi

stage "Verify HTTPS and update GitHub deployments"
say "DNS changes can take time. This check waits up to ten minutes; re-run later if propagation is slower."
CURL_DOH_ARGS=()
if curl --help all 2>/dev/null | grep -q -- '--doh-url'; then
  CURL_DOH_ARGS=(--doh-url https://cloudflare-dns.com/dns-query)
fi
healthy=0
for _ in $(seq 1 60); do
  if curl --fail --silent "$PUBLIC_URL/api/health" >/dev/null 2>&1 || {
    ((${#CURL_DOH_ARGS[@]} > 0)) &&
      curl "${CURL_DOH_ARGS[@]}" --fail --silent "$PUBLIC_URL/api/health" >/dev/null 2>&1
  }; then
    healthy=1
    break
  fi
  sleep 10
done
if [[ "$healthy" != "1" ]]; then
  warn "$PUBLIC_URL is not ready yet. No GitHub deployment address was changed."
  warn "Wait for DNS propagation, then re-run this wizard."
  exit 1
fi
write_env PUBLIC_URL "$PUBLIC_URL"
ROOT_HEADERS=""
if ! ROOT_HEADERS="$(curl --silent --show-error --output /dev/null --dump-header - --max-redirs 0 "http://$BASE_DOMAIN" | tr -d '\r')"; then
  if ((${#CURL_DOH_ARGS[@]} > 0)); then
    ROOT_HEADERS="$(curl "${CURL_DOH_ARGS[@]}" --silent --show-error --output /dev/null --dump-header - --max-redirs 0 "http://$BASE_DOMAIN" | tr -d '\r')" || ROOT_HEADERS=""
  fi
fi
ROOT_STATUS="$(printf '%s\n' "$ROOT_HEADERS" | awk 'NR == 1 { print $2 }')"
ROOT_LOCATION="$(printf '%s\n' "$ROOT_HEADERS" | awk 'tolower($1) == "location:" { print $2; exit }')"
if [[ "$ROOT_STATUS" != "301" || "${ROOT_LOCATION%/}" != "$PUBLIC_URL" ]]; then
  warn "The HTTP root domain must return 301 with Location: $PUBLIC_URL"
  warn "Observed status: ${ROOT_STATUS:-missing}; location: ${ROOT_LOCATION:-missing}"
  warn "Wait for DNS propagation or correct the DNSZi rule, then re-run this wizard."
  exit 1
fi
set_var PUBLIC_URL "$PUBLIC_URL"
GITHUB_PUBLIC_URL="$(gh variable get PUBLIC_URL --repo "$GITHUB_REPOSITORY" --json value --jq '.value' 2>/dev/null || true)"
if [[ "$GITHUB_PUBLIC_URL" != "$PUBLIC_URL" ]]; then
  warn "GitHub PUBLIC_URL does not equal $PUBLIC_URL, so setup is not complete."
  exit 1
fi
say "JobLens is healthy at $PUBLIC_URL and the HTTP root domain returns the required 301 redirect."
open_url "$PUBLIC_URL"
pause "After confirming the JobLens page opens, press Enter."

finish
