#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE=".env.aws"
AWS_REGION="ap-northeast-2"
GITHUB_REPOSITORY="hyunbeomlee1227-dev/joblens"

banner "JobLens AWS setup"

stage "Verify the release candidate"
say "The same formatting, type, build, and browser checks used by CI must pass before AWS changes begin."
for command in node npm; do
  if ! command -v "$command" >/dev/null 2>&1; then
    warn "$command is required before continuing."
    exit 1
  fi
done
npm ci
npx playwright install chromium
npm run format:check
npm run typecheck
npm test

stage "Confirm the AWS account and cost alerts"
say "This creates an always-on EC2 instance in Seoul, CloudFront HTTPS, ECR, logs, alarms, and a monthly budget."
for command in aws docker gh git curl; do
  if ! command -v "$command" >/dev/null 2>&1; then
    warn "$command is required before continuing."
    exit 1
  fi
done
AWS_ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
say "AWS account: $AWS_ACCOUNT_ID"
say "AWS region: $AWS_REGION (Seoul)"
if ! confirm "Create billable AWS resources in this account?"; then
  say "No AWS resources were changed."
  exit 0
fi
ask AWS_BUDGET_EMAIL "Email address for budget and service alerts:"
if [[ -z "$AWS_BUDGET_EMAIL" ]]; then
  warn "An alert email is required."
  exit 1
fi
ask AWS_MONTHLY_BUDGET "Monthly budget in USD [Enter uses 20]:"
AWS_MONTHLY_BUDGET="${AWS_MONTHLY_BUDGET:-20}"
write_env AWS_BUDGET_EMAIL "$AWS_BUDGET_EMAIL"
write_env AWS_MONTHLY_BUDGET "$AWS_MONTHLY_BUDGET"

stage "Create the registry, short-lived deploy role, and budget"
say "CloudFormation will create ECR, a GitHub OIDC role, and three budget thresholds."
aws cloudformation deploy \
  --region "$AWS_REGION" \
  --stack-name joblens-test-bootstrap \
  --template-file infra/aws/bootstrap.yml \
  --capabilities CAPABILITY_NAMED_IAM \
  --no-fail-on-empty-changeset \
  --parameter-overrides \
    BudgetEmail="$AWS_BUDGET_EMAIL" \
    MonthlyBudgetAmount="$AWS_MONTHLY_BUDGET"
ECR_REPOSITORY_URI="$(aws cloudformation describe-stacks --region "$AWS_REGION" --stack-name joblens-test-bootstrap --query "Stacks[0].Outputs[?OutputKey=='EcrRepositoryUri'].OutputValue | [0]" --output text)"
ECR_REPOSITORY_ARN="$(aws cloudformation describe-stacks --region "$AWS_REGION" --stack-name joblens-test-bootstrap --query "Stacks[0].Outputs[?OutputKey=='EcrRepositoryArn'].OutputValue | [0]" --output text)"
AWS_ROLE_ARN="$(aws cloudformation describe-stacks --region "$AWS_REGION" --stack-name joblens-test-bootstrap --query "Stacks[0].Outputs[?OutputKey=='GitHubDeployRoleArn'].OutputValue | [0]" --output text)"
set_var AWS_REGION "$AWS_REGION"
set_var AWS_ROLE_ARN "$AWS_ROLE_ARN"
set_var ECR_REPOSITORY_URI "$ECR_REPOSITORY_URI"

stage "Publish the first immutable application image"
say "The initial image is tagged with the current Git commit and pushed to private ECR."
IMAGE_TAG="bootstrap-$(git rev-parse --short=12 HEAD)"
IMAGE_URI="$ECR_REPOSITORY_URI:$IMAGE_TAG"
aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "${ECR_REPOSITORY_URI%%/*}"
if aws ecr describe-images --region "$AWS_REGION" --repository-name joblens-test --image-ids imageTag="$IMAGE_TAG" >/dev/null 2>&1; then
  note "The immutable $IMAGE_TAG image already exists; reusing it."
else
  docker build --build-arg DEPLOYMENT_VERSION="$IMAGE_TAG" -t "$IMAGE_URI" .
  docker push "$IMAGE_URI"
fi

stage "Create the Seoul runtime and public HTTPS endpoint"
say "Only CloudFront can reach the instance over HTTP; administration uses AWS Systems Manager, not SSH."
CLOUDFRONT_PREFIX_LIST_ID="$(aws ec2 describe-managed-prefix-lists --region "$AWS_REGION" --filters Name=prefix-list-name,Values=com.amazonaws.global.cloudfront.origin-facing --query 'PrefixLists[0].PrefixListId' --output text)"
if [[ -z "$CLOUDFRONT_PREFIX_LIST_ID" || "$CLOUDFRONT_PREFIX_LIST_ID" == "None" ]]; then
  warn "AWS did not return the CloudFront origin prefix list."
  exit 1
fi
aws cloudformation deploy \
  --region "$AWS_REGION" \
  --stack-name joblens-test-runtime \
  --template-file infra/aws/runtime.yml \
  --capabilities CAPABILITY_IAM \
  --no-fail-on-empty-changeset \
  --parameter-overrides \
    ImageUri="$IMAGE_URI" \
    EcrRepositoryArn="$ECR_REPOSITORY_ARN" \
    EcrRepositoryUri="$ECR_REPOSITORY_URI" \
    NotificationEmail="$AWS_BUDGET_EMAIL" \
    CloudFrontOriginPrefixListId="$CLOUDFRONT_PREFIX_LIST_ID"
EC2_INSTANCE_ID="$(aws cloudformation describe-stacks --region "$AWS_REGION" --stack-name joblens-test-runtime --query "Stacks[0].Outputs[?OutputKey=='InstanceId'].OutputValue | [0]" --output text)"
PUBLIC_URL="$(aws cloudformation describe-stacks --region "$AWS_REGION" --stack-name joblens-test-runtime --query "Stacks[0].Outputs[?OutputKey=='PublicUrl'].OutputValue | [0]" --output text)"
CLOUDFRONT_DISTRIBUTION_ID="$(aws cloudformation describe-stacks --region "$AWS_REGION" --stack-name joblens-test-runtime --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue | [0]" --output text)"
set_var EC2_INSTANCE_ID "$EC2_INSTANCE_ID"
set_var PUBLIC_URL "$PUBLIC_URL"
set_var CLOUDFRONT_DISTRIBUTION_ID "$CLOUDFRONT_DISTRIBUTION_ID"

stage "Enable the JobLens cost view"
say "The Project=JobLens tag separates this test environment from other AWS charges in Cost Explorer and its budget."
if aws ce update-cost-allocation-tags-status --cost-allocation-tags-status TagKey=Project,Status=Active >/dev/null 2>&1; then
  say "The Project cost-allocation tag is active."
else
  warn "AWS can take up to 24 hours to make a new cost tag available for activation."
  open_url "https://console.aws.amazon.com/billing/home#/tags"
  step "When Project appears under User-defined cost allocation tags, select it and choose Activate."
  pause "Press Enter after activating it, or continue and return to this stage tomorrow."
fi
open_url "https://console.aws.amazon.com/costmanagement/home#/cost-explorer"
step "In Cost Explorer, filter Tag → Project → JobLens to see only this application's AWS cost."
pause "Press Enter after confirming the cost path. New cost data may take up to 24 hours to appear."

stage "Verify the service and finish notifications"
say "The instance may need several minutes to install Docker and start JobLens."
ready=0
for _ in $(seq 1 60); do
  ping_status="$(aws ssm describe-instance-information --region "$AWS_REGION" --filters Key=InstanceIds,Values="$EC2_INSTANCE_ID" --query 'InstanceInformationList[0].PingStatus' --output text 2>/dev/null || true)"
  if [[ "$ping_status" == "Online" ]]; then
    ready=1
    break
  fi
  sleep 10
done
if [[ "$ready" != "1" ]]; then
  warn "The instance did not become manageable within ten minutes. Check the joblens-test-runtime stack events."
  exit 1
fi

healthy=0
for _ in $(seq 1 60); do
  if curl --fail --silent "$PUBLIC_URL/api/health" >/dev/null; then
    healthy=1
    break
  fi
  sleep 10
done
if [[ "$healthy" != "1" ]]; then
  warn "The public health endpoint did not become ready within ten minutes."
  exit 1
fi
say "JobLens is available at $PUBLIC_URL"
step "Open the AWS email sent to $AWS_BUDGET_EMAIL and confirm the SNS subscription for service alarms."
open_url "$PUBLIC_URL"
open_url "https://console.aws.amazon.com/billing/home#/budgets"
open_url "https://$AWS_REGION.console.aws.amazon.com/cloudwatch/home?region=$AWS_REGION#dashboards:name=joblens-test-operations"
pause "After checking the site and confirming the alarm email, press Enter."

finish
