#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ENV_FILE=".env.auth"
AWS_REGION="${AWS_REGION:-ap-northeast-2}"
APP_ORIGIN="${APP_ORIGIN:-https://www.hyunbeom.site}"
RUNTIME_STACK="${RUNTIME_STACK:-joblens-test-runtime}"
AUTH_STACK="${AUTH_STACK:-joblens-test-auth}"

banner "JobLens Google login setup"

# ── Example stage: replace with your real steps ───────────────────────────
stage "Verify AWS and the running service"
say "This checks the existing Seoul runtime without stopping the public service."
for command_name in aws curl openssl; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    warn "$command_name is required before this wizard can continue."
    exit 1
  fi
done
aws sts get-caller-identity >/dev/null
AWS_ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
EC2_INSTANCE_ID="$(aws cloudformation describe-stacks --region "$AWS_REGION" --stack-name "$RUNTIME_STACK" --query "Stacks[0].Outputs[?OutputKey=='InstanceId'].OutputValue | [0]" --output text)"
RUNTIME_ROLE_NAME="$(aws cloudformation describe-stack-resource --region "$AWS_REGION" --stack-name "$RUNTIME_STACK" --logical-resource-id InstanceRole --query 'StackResourceDetail.PhysicalResourceId' --output text)"
COGNITO_DOMAIN_PREFIX="joblens-${AWS_ACCOUNT_ID}"
GOOGLE_REDIRECT_URI="https://${COGNITO_DOMAIN_PREFIX}.auth.${AWS_REGION}.amazoncognito.com/oauth2/idpresponse"
say "AWS account: $AWS_ACCOUNT_ID"
say "Runtime instance: $EC2_INSTANCE_ID"
say "Google redirect URI: $GOOGLE_REDIRECT_URI"
curl --fail --silent "$APP_ORIGIN/api/health" >/dev/null
note "The existing public release is healthy and remains online during setup."
pause "Press Enter to configure Google OAuth."

stage "Create the Google web client"
say "Google is the only sign-in provider. The client secret stays local until CloudFormation stores it in AWS Secrets Manager."
open_url "https://console.cloud.google.com/auth/clients"
step "Select the Google Cloud project you want to use. If Google Auth Platform is not configured, complete Branding and Audience first."
step "For Audience, choose External. While the app is in Testing, add your Google account as a test user."
step "On Clients, create an OAuth client with application type 'Web application' and name it 'JobLens'."
step "Under Authorized redirect URIs, add this exact URI: $GOOGLE_REDIRECT_URI"
step "Create the client, then copy its Client ID and Client secret. Do not add either value to GitHub."
ask GOOGLE_CLIENT_ID "Paste the Google Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Google Client secret:"
if [[ -z "$GOOGLE_CLIENT_ID" || -z "$GOOGLE_CLIENT_SECRET" ]]; then
  warn "Both Google values are required."
  exit 1
fi
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
chmod 600 "$ENV_FILE"

stage "Deploy Cognito and Candidate storage"
say "CloudFormation creates a Google-only Cognito user pool, encrypted DynamoDB table, Secrets Manager secret, and least-privilege runtime policy."
OAUTH_TRANSACTION_KEY="$(_existing OAUTH_TRANSACTION_KEY || true)"
if [[ -z "$OAUTH_TRANSACTION_KEY" ]]; then
  OAUTH_TRANSACTION_KEY="$(openssl rand -base64 32 | tr -d '\r\n')"
  write_env OAUTH_TRANSACTION_KEY "$OAUTH_TRANSACTION_KEY"
fi
aws cloudformation deploy \
  --region "$AWS_REGION" \
  --stack-name "$AUTH_STACK" \
  --template-file infra/aws/auth.yml \
  --capabilities CAPABILITY_IAM \
  --no-fail-on-empty-changeset \
  --parameter-overrides \
    AppOrigin="$APP_ORIGIN" \
    CognitoDomainPrefix="$COGNITO_DOMAIN_PREFIX" \
    GoogleClientId="$GOOGLE_CLIENT_ID" \
    GoogleClientSecret="$GOOGLE_CLIENT_SECRET" \
    OAuthTransactionKey="$OAUTH_TRANSACTION_KEY" \
    RuntimeRoleName="$RUNTIME_ROLE_NAME"
DEPLOYED_REDIRECT_URI="$(aws cloudformation describe-stacks --region "$AWS_REGION" --stack-name "$AUTH_STACK" --query "Stacks[0].Outputs[?OutputKey=='GoogleAuthorizedRedirectUri'].OutputValue | [0]" --output text)"
if [[ "$DEPLOYED_REDIRECT_URI" != "$GOOGLE_REDIRECT_URI" ]]; then
  warn "The deployed redirect URI differs from the Google value: $DEPLOYED_REDIRECT_URI"
  exit 1
fi
note "The Google secret is now server-side in AWS Secrets Manager; it was not written to GitHub."
pause "Press Enter to verify the Google client."

stage "Verify the Google redirect URI"
open_url "https://console.cloud.google.com/auth/clients"
step "Open the JobLens web client you just created."
step "Confirm Authorized redirect URIs contains exactly: $DEPLOYED_REDIRECT_URI"
step "Save if you made a correction, then wait a few minutes for Google to apply it."
pause "Press Enter after the exact redirect URI is saved."

stage "Enable container access to the instance role"
say "The Next.js container obtains short-lived AWS credentials from the EC2 role. IMDSv2 stays required; hop limit 2 lets the container reach it."
aws ec2 modify-instance-metadata-options \
  --region "$AWS_REGION" \
  --instance-id "$EC2_INSTANCE_ID" \
  --http-endpoint enabled \
  --http-tokens required \
  --http-put-response-hop-limit 2 >/dev/null
aws ec2 wait instance-status-ok --region "$AWS_REGION" --instance-ids "$EC2_INSTANCE_ID"
note "No access key was copied into Docker, GitHub, or the application."
pause "Press Enter to verify the live login journey."

stage "Verify login, preferences, logout, and deletion"
say "First deploy this revision through the normal CI workflow if it is not live yet. Then complete the checks below in your browser."
open_url "$APP_ORIGIN/auth/google"
step "Sign in with Google and confirm JobLens returns to the Discovery page as a Candidate."
step "Choose role, 수도권 region, and work arrangement; save them and confirm Discovery uses those defaults."
step "Log out and confirm the Candidate controls disappear. Sign in again to verify a fresh session works."
if confirm "Delete this test account now? This permanently removes its sessions and saved preferences."; then
  step "Use '계정 삭제' in JobLens, then confirm you are signed out and can create a fresh Google session later."
  pause "Press Enter after account deletion succeeds."
else
  note "Account deletion was left for a later manual verification."
fi
curl --fail --silent "$APP_ORIGIN/api/health" >/dev/null
note "Public health is still good. Authentication verification requires the browser checks above."
# ──────────────────────────────────────────────────────────────────────────

finish
